name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check lint
        run: ./gradlew lint
      - name: Build with Gradle
        run: ./gradlew build

      - name: Distribute App
        run: |
            curl \
             -H "Authorization: token ${{secrets.DEPLOYGATE_API_KEY}}" \
             -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
             -F "message=Any message" \
             -F "distribution_key=${{secrets.DEPLOYGATE_DISTRIBUTION_KEY}}" \
             -F "release_note=Release Note" \
             "https://deploygate.com/api/users/johanforce/apps"



